import type { DynamicSubmission } from "../types/submission";

interface Props {
  data: DynamicSubmission;
}

export default function DocumentTemplate({ data }: Props) {
  return (
    <>
      {/* CSS สำหรับตอน print โดยเฉพาะ */}
      <style>{`
        @media print {
          @page {
            size: A4;
            margin: 0;
          }
          body {
            margin: 0;
            padding: 0;
          }
          #pdf-content {
            width: 210mm;
            min-height: 297mm;
            padding: 20mm;
            box-shadow: none !important;
            border: none !important;
            page-break-after: avoid;
          }
        }
      `}</style>

      <div
        id="pdf-content"
        className="w-[210mm] bg-white p-[20mm] mx-auto text-gray-800 font-sans"
        style={{
          boxSizing: "border-box",
          height: "297mm",          // ตายตัวเลย ไม่ใช้ min
          position: "relative",     // ให้ footer absolute ได้
          overflow: "hidden",       // ไม่ให้ล้น
        }}
      >
        {/* Header */}
        <div className="border-b-4 border-[#9E76B4] pb-4 mb-6 flex justify-between items-end">
          <div>
            <h1 className="text-2xl font-bold uppercase text-gray-900">{data.gameTitle}</h1>
            <p className="text-sm text-gray-500">Ethical Monetization Design Report</p>
          </div>
          <div className="text-right">
            <p className="text-xs text-gray-400">Date: {new Date(data.timestamp).toLocaleDateString()}</p>
          </div>
        </div>

        {/* Blocks */}
        <div className="space-y-6">
          {data.blocks.map((block: any, i: number) => (
            <section key={i} style={{ breakInside: "avoid" }}>
              <h2 className="text-md font-bold text-[#9E76B4] border-l-4 border-[#9E76B4] pl-2 mb-3 uppercase tracking-wider">
                {block.title}
              </h2>

              {block.type === 'key-value' && (
                <div className="grid grid-cols-2 gap-4 bg-gray-50 p-4 rounded-lg">
                  {Object.entries(block.data).map(([k, v]: any) => (
                    <div key={k}>
                      <p className="text-[10px] text-gray-400 uppercase font-bold">{k}</p>
                      <p className="font-medium text-gray-800">{v || "-"}</p>
                    </div>
                  ))}
                </div>
              )}

              {block.type === 'header' && (
                <div className="p-2 text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                  {block.data}
                </div>
              )}

              {block.type === 'analysis-box' && (
                <div className="p-4 border-2 border-green-100 rounded-lg bg-green-50/30">
                  <p className="italic text-gray-700 leading-relaxed text-sm">"{block.data.summary}"</p>
                </div>
              )}

              {block.type === 'list' && (
                <ul className="space-y-2 ml-2">
                  {block.data.map((item: any, idx: number) => (
                    <li key={idx} className="text-sm flex gap-3 items-start">
                      <span className="text-[#9E76B4] font-bold mt-0.5">•</span>
                      <span className="text-gray-700">
                        {item.label || item.title}
                        {item.description && (
                          <span className="text-gray-500 block text-xs mt-0.5">{item.description}</span>
                        )}
                      </span>
                    </li>
                  ))}
                </ul>
              )}
            </section>
          ))}
        </div>

        {/* Footer — absolute ติดล่างสุดเสมอ */}
        <div
          className="text-[10px] text-gray-400 text-center border-t border-dashed pt-4"
          style={{
            position: "absolute",
            bottom: "20mm",       // ห่างขอบล่างเท่า padding
            left: "20mm",
            right: "20mm",
          }}
        >
          <p>This document was generated by Ethical Monetization Designer AI assistant. CMU Game Design Program.</p>
        </div>
      </div>
    </>
  );
}